version: "3"
services:
  server:
    container_name: server
    hostname: server
    image: server:latest
    environment:
      PORT: 8080
    expose:
      - "8080"
  client:
    container_name: client
    image: client:latest
    environment:
      PORT: 8080
      HOSTNAME: server
      RESOURCE: example.com
    expose:
      - "8080"
    restart: "on-failure"
    depends_on:
     - server
